name: meetup_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_route: ^7.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  intl_translation: ^0.19.0
  injectable: any
  get_it: ^7.6.7
  collection: ^1.18.0
  http: ^1.2.1

dependency_overrides:
  intl: any

dev_dependencies:
  auto_route_generator: ^7.3.2
  injectable_generator: any
  intl_translation: ^0.19.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true